// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (service_name, price, user_id, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	UserID      pgtype.UUID `json:"user_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at FROM subscriptions
ORDER BY id
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSubscriptionCost = `-- name: SumSubscriptionCost :one
SELECT COALESCE(SUM(price), 0)::INTEGER AS total
FROM subscriptions
WHERE
    ($1::UUID IS NULL OR user_id = $1)
  AND ($2::TEXT IS NULL OR service_name = $2)
  AND start_date >= $3
  AND (end_date IS NULL OR end_date <= $4)
`

type SumSubscriptionCostParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceName *string     `json:"service_name"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

func (q *Queries) SumSubscriptionCost(ctx context.Context, arg SumSubscriptionCostParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumSubscriptionCost,
		arg.UserID,
		arg.ServiceName,
		arg.FromDate,
		arg.ToDate,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET service_name = $2,
    price        = $3,
    start_date   = $4,
    end_date     = $5,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID          int64       `json:"id"`
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
